apiVersion: v1
kind: Secret
metadata:
  name: medical-visits-mysql
  namespace: medical-visits
type: Opaque
stringData:
  MYSQL_DATABASE: medical_visits
  MYSQL_USER: medical_visits
  MYSQL_PASSWORD: CHANGE_ME
  MYSQL_ROOT_PASSWORD: CHANGE_ME
