apiVersion: v1
kind: Service
metadata:
  name: medical-visits-mysql
  namespace: medical-visits
  labels:
    app.kubernetes.io/name: medical-visits-mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: medical-visits
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: medical-visits-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
