apiVersion: v1
kind: Service
metadata:
  name: medical-visits-app
  namespace: medical-visits
  labels:
    app.kubernetes.io/name: medical-visits-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: medical-visits
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: medical-visits-app
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
      protocol: TCP
